### ISSUE TITLE
[2.0.3-r9 (100)] Sony xPeria Z / Android 5.1.1 - Wrong time display in notification - Follow user, unfollow and again follow

### ISSUE THREAD

**Issue by Priyanka-SoftwaresDoneRight** [Lomotif/lomotif-android-issues#815] opened 2017-01-06 12:12 UTC
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials (User A)

3. Tap on "Find User" icon and search for User-B
4.  Follow User-B and User-B will receive notification
5. Now, Unfollow User-B from User-A account
6. Check notification is deleted / removed from User-B's notification screen
7. Again, follow User-B from User-A's account
8. Refresh User-B notification screen and check whether time display is correct or not ("User-A is now following you. 12h")

Expected result: Time displayed in notification should be accurate and correct

Actual result: Wrong time displays in notification (12h)

![screenshot_2017-01-06-17-36-56](https://cloud.githubusercontent.com/assets/24950381/21717500/5e31b8e6-d437-11e6-8600-fd718c7842e4.png)

**Comment by Aboli-Testershub** [comment] 2017-01-06 13:44
@xiuie Duplicate of #780

**Closed as completed** 2017-01-09 05:55 UTC
Labels: Duplicate
