### ISSUE TITLE
[1.6.0-r4 (64)] Asus Zenfone Go / Android 5.1 - Login with invalid Email - Change Email and login with updated email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#570] opened 2016-11-14 08:53 UTC
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential through Email id and password
3. Tap on setting menu
4. Click on Email option
5. Change Email address and click on Tick -> Email address will be updated
6. Logout from account
7. Again tap on Sign in
8. Try to login with old Email address and password
9. Check whether user is able to login or not

Expected result: User should not able to login with old Email address and password

Actual result: User can login with old Email and Password even though he has updated  Email

**Comment by testershub** [comment] 2016-11-14 09:41
@xiuie I can't reproduce this issue for build [1.6.0-r4 (64)] on Samsung Galaxy Note 4 / 6.0.1.
Warning message "Oops, unable to login using email at..." is displayed when user try to sign in with old email id.

**Comment by xiuie** [comment] 2016-11-14 10:14
Please try again @hiteshbheda With a freshly made-up email address. I suspect you already have an account with that email address. Let me know if I can close this bug.

**Comment by Dipamit** [comment] 2016-11-14 11:26
@xiuie : Able to reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r4(64)

Note: Email address is updated, still i can Login with Old email address.

**Comment by hiteshbheda** [comment] 2016-11-14 16:02
@xiuie I have tried with new email address but still I can reproduce this issue

**Closed as completed** 2016-11-25 06:26 UTC
Labels: High (bug), Reproducible
