### ISSUE TITLE
Music is not playing in the created Limotif.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#52] opened 2016-04-04 09:57 UTC
Steps to Reproduce:-
1. Launch the application.
2. In "Get Started" Page tap on  the Created video. 
3. Tap on the music icon.  
4. Tap on My music tab and select any music.  
5. Tap on use music.
6. Check whether music is playing with video or not.

Actual result: Music is not playing in the created Limotif.

Expected result: Selected music should play with the video.

Environment: Micromax  P480/ android 5.0.1

**Comment by hiteshbheda** [comment] 2016-04-04 17:11
@xiuie Duplicate of #1

**Comment by xiuie** [comment] 2016-04-04 17:14
Thanks for pointing out @hiteshbheda That's helpful.

**Closed as completed by xiuie** 2016-04-04 17:14 UTC
Labels: Duplicate
