### ISSUE TITLE
[1.4.7 (43)] Asus Zenfone Go 4.5 / Android 5.1 - Error Message instead of search results - Go to Find Music and search for "Nickki Minijj"

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#416] opened 2016-09-04 05:53 UTC
Frequency: Every time

Action:
1. Launch the app
2. Tap on "Start" button
3. Select any image / motif
4. Go to Find Music tab
5. Search for keyword "Nicki minaj"
6. It will return search results
7. Now search for "Nickki minijj"
8. Check whether you are getting search results or not

Expected result: Songs related to "Nicki minaj" should be displayed

Actual result: Searching for "Nickki minijj" displays Error message "No music under the search term "nickki minijj"

![screenshot_2016-09-04-11-18-12](https://cloud.githubusercontent.com/assets/9691390/18229308/03ac011c-7292-11e6-91ca-e19154990c56.png)

**Comment by testershub** [comment] 2016-09-06 06:42
@hiteshbheda @xiuie , I think we have already discussed this issue during last regression run, It's not a bug as there is mistake in the test case.

**Comment by xiuie** [comment] 2016-09-06 09:56
Agreed.. closing.. :)

**Closed as completed by xiuie** 2016-09-06 09:56 UTC
Labels: Not a bug

**Comment by hiteshbheda** [comment] 2016-12-05 06:08
@xiuie I can reproduce this issue for build [1.6.0-r23 (83)] on Asus Zenfone Go / Android 5.1

![screenshot_2016-12-05-11-32-26](https://cloud.githubusercontent.com/assets/9691390/20875257/4829b506-badf-11e6-8d84-9e6d5438f1cb.png)
