### ISSUE TITLE
[1.0.15] Samsung galaxy S4 / Android 4.4.2: Application crash after user return from Find Music screen which return no results with disabled internet connection

### ISSUE THREAD

**Issue by kcherkas** [Lomotif/lomotif-android-issues#87] opened 2016-04-06 07:55 UTC
[1.0.15] Samsung galaxy S4 / Android 4.4.2: Application crash after user return from Find Music screen which return no results with disabled internet connection

Frequency: Every Time
Preconditions: disable internet connection
1. make sure what internet connection in disabled
2. run application
3. tap start
4. select any image at My video screen
5. proceed to Find Music screen
6. make search request which return no result e.g. "Sss" -> "An error has occured" message displayed
7. use back to return to previous screen

Expected results: My video screen displayed
Actual results: application crashed

[crash at search.txt](https://github.com/Lomotif/lomotif-android-issues/files/205962/crash.at.search.txt)

**Comment by hiteshbheda** [comment] 2016-04-06 17:30
@xiuie @jpaulo1205 I can reproduce this issue every time for build [1.0.15] on Asus Zenfone Go 4.5 / Android 5.1

**Comment by jpaulo1205** [comment] 2016-04-07 20:20
Note: Fixed in 1.0.16

**Comment by kcherkas** [comment] 2016-04-08 08:20
Verified in v1.0.16 at Samsung galaxy S4, android 4.4.2. No crash

**Comment by vysohanych** [comment] 2016-04-23 18:24
I can't reproduce it on build 1.0.18 on Asus Nexus 7 Android 5.1.1.

**Comment by xiuie** [comment] 2016-04-23 18:44
Thanks @kcherkas for verifying.. that's really helpful.

**Closed as completed by xiuie** 2016-04-23 18:44 UTC
Labels: High (bug)
