### ISSUE TITLE
[1.5.0-r5 (53)] Asus Zenfone Go / Android 5.1 - Black screen appears - Create lomotif with Panorama image

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#517] opened 2016-10-20 11:03 UTC
Frequency: Every time

Action:
1. Launch the app
2. Tap on START
3. Select Panorama image from Camera roll
4. Skip music and create lomotif
5. On Preview screen check lomotif plays with correct display or not

Expected result: Lomotif should be played perfectly

Actual result: Black screen appears on Preview screen during lomotif playing

**Comment by testershub** [comment] 2016-10-20 11:14
@xiuie Duplicate of #164

**Closed as completed** 2016-10-20 11:20 UTC
Labels: Duplicate
