### ISSUE TITLE
[1.0.19.1] Samsung Galaxy Note 2/4.4.2, Samsung Galaxy Note4/5.0.1, Samsung Galaxy S4/5.0.1- Application crashes when user selects a video (which has no thumbnail) from "Lomotif" folder and taps on next button on "Add Music" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#185] opened 2016-05-02 07:06 UTC
Frequency: Everytime

Action: 
Precondition: User should have "Lomotif" folder on "Add Photos & Videos" screen which have created some Lomotif videos earlier.
User should have at least one video which doesn't have thumbnail (i.e when user try to play this video it displays "Can't play this video" message.
1. Launch the application. 
2. Tap on "Start" button.
3. Tap on "Lomotif" folder.
4. Video list will be displayed.
5. Select a video from list which doesn't have thumbnail (i.e when user try to play this video it displays "Can't play this video" message.
6. Tap on "Next(>)" button and reach to "Add Music" screen.
8. Tap on "Next" button without selecting music or by selecting music from list.
9.
![lomotif_video](https://cloud.githubusercontent.com/assets/18608449/14948777/9e8aea10-1061-11e6-84ac-9cd23ba190fd.jpg)
 Warning message will be displayed, tap on "OK" button. (If user has not selected any music)
10. Check if application crashes.

Expected Result: Application should not crash.

Actual Result: Application crashes when user selects a video (which has no thumbnail) from "Lomotif" folder and taps on next button on "Add Music" screen.

Please refer screenshot for more details-
Please refer video link for more details-
http://www.screencast.com/t/kWVZhRc2sW

**Comment by testershub** [comment] 2016-05-02 07:08
Please check attached log-
[#185_crash_log.txt](https://github.com/Lomotif/lomotif-android-issues/files/244628/185_crash_log.txt)

**Comment by hiteshbheda** [comment] 2016-05-02 09:26
@xiuie Duplicate of #166 and Similar to #156 

I can't reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1

**But, on create screen lomotif is continue loading but application does not crash**

**Closed as completed** 2016-05-02 16:48 UTC
