### ISSUE TITLE
[1.4.5(34)] Samsung Galaxy Note 4 / 6.0.1 , Samsung Galaxy Note 2 / 4.4.2 - Preview is not displayed on "Create" screen when user creates lomotif with images from "Retrica" folder.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#343] opened 2016-08-06 10:11 UTC
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select images from "Retrica" folder.
3: Skip the music and proceed to "Create" screen.
4: Check if preview is not displayed on "Create" screen.

Expected result: Preview should be displayed when user creates lomotif with images from "Retrica" folder.

Actual result: Preview is not displayed on "Create" screen when user creates lomotif with images from "Retrica" folder, black screen is displayed.

Note: Issue is specifically observed when image doesn't have any effect.

Refer screenshot for more details.

**Comment by testershub** [comment] 2016-08-06 10:12
![preview](https://cloud.githubusercontent.com/assets/18608449/17456181/5a68105c-5bec-11e6-8913-45624be2880a.jpg)

**Comment by vysohanych** [comment] 2016-08-06 20:39
@xiuie I can't reproduce it on build 1.4.5 (34) on LG Nexus 5X Android 6.0.1 because "Retrica" folder is missing

**Comment by hiteshbheda** [comment] 2016-08-08 11:26
@xiuie  I can't reproduce this issue for Live build 1.4.4 (33) on Asus Zenfone Go / Android 5.1 because "Retrica" folder is not available

**Comment by hiteshbheda** [comment] 2016-08-08 17:45
@xiuie I can reproduce this issue for Live build 1.4.4 (33) on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment] 2016-08-26 10:47
I can reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go 4.5 / Android 5.1

**But it works perfectly for Retrica Videos. only Image preview is Black.**

**Comment by hiteshbheda** [comment] 2016-08-29 16:49
@xiuie I can reproduce this issue for build [1.4.6-r2 (38)] on Asus Zenfone Go / Android 5.1

**Comment by hiteshbheda** [comment] 2016-09-06 06:27
@xiuie This issue is reproducible for Retrica images only for build 1.4.7 (43) on Asus Zenfone Go / Android 5.1

But it is not reproducible for Retrica Videos

**Comment by testershub** [comment] 2016-09-14 08:20
@xiuie I can still reproduce this issue for build [1.4.7-r2 (46)] on Samsung Galaxy Note 4 / 6.0.1.

Black frame is displayed on "Preview".

**Comment by testershub** [comment] 2016-10-10 11:40
@xiuie I can still reproduce this issue for build [1.5.0-r1 (49)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by hiteshbheda** [comment] 2016-10-11 09:59
@xiuie **I can reproduce this issue ONLY FOR RETRICA IMAGES** for build [1.5.0-r1 (49)] on Asus Zenfone Go 4.5 / Android 5.1

**But it works perfectly for Retrica Videos. only Image preview is Black.**

**Comment by Aboli-Testershub** [comment] 2017-01-28 06:13
@xiuie I can't reproduce this issue for build [2.0.5-r4 (114)] on Samsung Galaxy Note 4 / 6.0.1

**Comment by solgems** [comment] 2017-03-14 07:24
Black frames image loading issue should be fixed. submit new ticket if necessary.

**Closed as completed by solgems** 2017-03-14 07:24 UTC
Labels: Reproducible

**Comment by Aboli-Testershub** [comment] 2017-03-15 04:07
@solgems, Ok.
