### ISSUE TITLE
[1.5.0-r6 (54)] Asus Zenfone Go / Android 5.1 - Alert message not display on Audio change - Create lomotif with any music and change audio

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#529] opened 2016-10-22 04:14 UTC
Frequency: Every time

Action:
1. Launch the app
2. Tap on START
3. Select any asset
4. Add any song from Find Music or My Music tab and create lomotif
5. On preview screen lomotif starts playing
6. Click on Audio change icon
7. It will navigate you on Find Music / My Music screen
8. Don't select any song and click on Next
9. Check whether you are getting any alert message or not

Expected result: Alert message should be displayed like "Are you sure you want to proceed without adding music?..."

Actual result: No alert message display when user change audio but not select any song

**Comment by testershub** [comment] 2016-10-24 10:55
@xiuie Duplicate of #410

**Closed as completed** 2016-10-28 03:56 UTC
Labels: Duplicate
