### ISSUE TITLE
[1.5.0-r6 (54)] Asus Zenfone Go / Android 5.1 - "webm Unsupported Format" message display - Add video from "Vine" folder

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#532] opened 2016-10-25 05:33 UTC
Frequency: Every time

Pre-requisite: Install "Vine" app and record and save one video in it

Action: 
1. Launch the app.
2. Tap on "START" 
3. On "Add Photos & Videos" screen select "vine" folder.
4. Check whether "webm Unsupported Format" is displayed for video in "vine" folder or not
5. Also check whether user is able to select any video from this folder or not

Expected result: 
1. There should be no Error display on video thumbnails
2. User should be able to select videos from "Vine" folder

Actual result: 
1. Error "webm Unsupported Format" is displayed on video thumbnail in "Vine" folder
2. User is unable to select videos from "Vine" folder

![screenshot_2016-10-25-10-55-18](https://cloud.githubusercontent.com/assets/9691390/19674019/92cf27ba-9aa2-11e6-9c16-32f8e5f1714c.png)

**Comment by testershub** [comment] 2016-10-25 05:38
@xiuie Duplicate of #367

**Closed as completed** 2016-10-25 11:26 UTC
Labels: Duplicate
