### ISSUE TITLE
[1.0.19.1] Samsung Galaxy  S6/6.0.1- Music at "Create" screens keeps on playing in the background even when the user is on a call.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#168] opened 2016-04-29 13:53 UTC
Frequency: Every Time.

Preconditions:
-User should have at least one lomotif saved.
-User should be on "Create" screen.

Action:
1: Launch the application and tap on the saved lomotif.
2: User will be navigated to "Create" screen, play the lomotif and answer the call.
3: Check if lomotif keeps on playing in the background.

Expected result: Lomotif should pause as soon as user received the call.

Actual result: Lomotif keeps on playing in the background even when the user is on the call.

**Comment by hiteshbheda** [comment] 2016-04-29 18:23
@xiuie Duplicate of #102

**Closed as completed** 2016-04-30 19:28 UTC
