### ISSUE TITLE
[1.1.2(22)] Samsung Galaxy Note 2/4.4.0, Samsung Galaxy Note 4/6.0.1, Samsung Galaxy S4/5.0.1- Application is crashing when user selects a video from "Lomotif" folder which has no preview image and navigate to "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#225] opened 2016-06-18 11:42 UTC
Frequency: Every time.

Action: 
1. Launch the application. 
2. Tap on "Start" button.
3. Select a video form "Lomotif" folder which has no preview (thumbnail is not displayed).
4. Tap on "Next" button and select a song.
5. Tap on "Next" button.
6: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing.

Refer the following video link for more details:
http://www.screencast.com/t/ODHZSklgQDo

**Comment by vysohanych** [comment] 2016-06-18 15:23
@xiuie Duplicate of #213 or #156 

I can reproduce it on build 1.1.2.(22) on Samsung Galaxy Tab S 10.5 Android 4.4.2.

**Comment by hiteshbheda** [comment] 2016-06-18 18:37
@xiuie Duplicate #213 #156 

I can't reproduce this issue for build [1.1.2 (22)] on Asus Zenfone Go 4.5 / Android 5.1

**Instead of crashing of App, It shows Black screen. But app does not crash**

**Comment by xiuie** [comment] 2016-06-20 12:37
Will log #213 Thanks everyone

**Closed as completed by xiuie** 2016-06-20 12:37 UTC
Labels: Duplicate
