### ISSUE TITLE
Errror 404 is displaying while the user tap on the "terms of use & privacy policy" link.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#54] opened 2016-04-04 12:25 UTC
Step to reproduce:
1.Launch the application. 
2.In "Get started" page tap on "settings" button.
3.Tap on the "Terms of use policy" link.
4.Check whether the content is displaying or not.

Actual result: Errror 404 is displaying while the user tap on the "terms of use & privacy policy" link.

Expected result:The content should display.

Environment: Micromax P480/ android 5.0.1 
![404 error](https://cloud.githubusercontent.com/assets/12474351/14247804/5ad2f63e-fa8e-11e5-9869-d2fede832485.jpg)

**Comment by hiteshbheda** [comment] 2016-04-04 14:57
@xiuie Duplicate of #26

**Comment by xiuie** [comment] 2016-04-04 17:04
@tsukisa Can pass the link you use for T&Cs to Juan and then assign this bug to him?

**Closed as completed by xiuie** 2016-04-04 17:04 UTC
Labels: Duplicate
