### ISSUE TITLE
[1.5.0-r3 (51)] Asus Zenfone Go / Android 5.1 - "Enter Title" value does not save - Create and save lomotif and reload again

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#497] opened 2016-10-17 17:25 UTC
Frequency: Every time

Action:
1. Launch the app
2. Tap on START
3. Select any image from Camera roll folder
4. Skip music and create lomotif
5. Add any text for "Enter Title"
6. Save lomotif
7. Load recently saved lomotif
8. Check whether "Enter Title" value display on the screen or not

Expected result: "Enter Title" value should be displayed on preview screen

Actual result: "Enter Title" value does not display on the preview screen

**Comment by testershub** [comment] 2016-10-18 08:00
@xiuie Duplicate of #458

**Comment by vysohanych** [comment] 2016-10-19 11:44
@xiuie I can reproduce it on build 1.5.0-r4 (52) on LG Nexus 5X Android 6.0.1

**Closed as completed** 2016-10-20 04:17 UTC
