### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Audio not added - create lomotif and add song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#1] opened 2016-03-15 16:28 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 photos from Camera folder from My Video tab
4. Select any song from My Music tab
5. Play lomotif

Expected result: Lomotif should be played with audio

Actual result: Audio added but unable to play

![screenshot_2016-03-15-21-51-53](https://cloud.githubusercontent.com/assets/9691390/13785270/f0940c44-eaf8-11e5-934e-8a7ee99e53dd.png)

![screenshot_2016-03-15-21-52-04](https://cloud.githubusercontent.com/assets/9691390/13785269/f093e7c8-eaf8-11e5-97e0-cab8495d2285.png)

**Comment by xiuie** [comment] 2016-03-18 20:17
@hiteshbheda Is this still an issue?

**Comment by hiteshbheda** [comment] 2016-03-19 03:54
@xiuie Yes, i can still replicate this issue.

**Comment by jpaulo1205** [comment] 2016-03-23 07:28
Note: Fixed for next build (1.0.14)

**Comment by vysohanych** [comment] 2016-03-31 15:12
@xiuie @jpaulo1205 Can't reproduce on build 1.0.14

**Comment by hiteshbheda** [comment] 2016-03-31 16:48
@xiuie @jpaulo1205 @vysohanych I can still reproduce it for build [1.0.14] on Sony xPeria Z / Android 5.1.1.

Actually, now songs added but unable to play. (no sound)

**Comment by kcherkas** [comment] 2016-04-04 09:02
Reproducible for build 1.0.14 on samsung galaxy S4, android 4.4.2. Lomotif clip created w/o sound.

**Comment by kcherkas** [comment] 2016-04-06 08:43
Reproducible for build 1.0.15 on samsung galaxy S4, android 4.4.2. Lomotif clip sometimes created w/o sound.

**Comment by vinay97t** [comment] 2016-04-06 09:40
Still the same issue is there.

**Comment by hiteshbheda** [comment] 2016-04-06 16:41
@xiuie @jpaulo1205 I can reproduce this Critical issue for build [1.0.15] on Asus Zenfone Go 4.5 / Android 5.1 and also on Sony xPeria Z / Android 5.1.1 every time.

**Comment by jpaulo1205** [comment] 2016-04-07 03:46
Sorry, misunderstood the issue. Issue occurs for file type other than .m4a. Note that some audio format are not supported.

Added fix for mp3 files and filter out unsupported formats

Note: Fixed in 1.0.16

**Comment by vysohanych** [comment] 2016-04-16 21:03
I can't reproduce it on build 1.0.18 on Asus Nexus 7 Android 5.1.1

**Comment by hiteshbheda** [comment] 2016-04-25 18:47
@xiuie @jpaulo1205 I can't reproduce this issue for android app build [1.0.18] on Asus Zenfone Go 4.5 / Android 5.1

**Closed as completed** 2016-04-28 22:36 UTC
Labels: Critical (bug)
