### ISSUE TITLE
[1.0.19.1] Samsung Galaxy Note 2/4.4.2- Continuos loading process is displayed when user try to change music from "Add Music" list.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#177] opened 2016-04-30 06:30 UTC
Frequency: Every Time

Action: 
1. Launch the application. 
2. Tap on "Start" button.
3. Select any image and tap on "Next"(>) button.
4. Reach to "Add Music" screen.
5. Select any music from "Add Music" section and tap on "Next" button.
6. Reach to "Create" screen.
7. Tap on "Music" icon and again reach to "Add Music" screen.
8. Again select another song from list and tap on "Next" button.
9. Check if continuos loading process is displayed.

Expected Result: Continuos loading process should not be displayed and user should be navigate to "Create" screen when user try to change music from "Add Music" list.

Actual Result: Continuos loading process is displayed when user try to change music from "Add Music" list.

Note: Please refer video link for more details-
http://www.screencast.com/t/Fh4gfcDq

**Comment by hiteshbheda** [comment] 2016-04-30 06:41
@xiuie I can't reproduce this issue for build [1.0.19.1] on Asus Zenfone Go 4.5 / Android 5.1

Duplicate of #162

**Closed as completed** 2016-04-30 19:32 UTC
Labels: Duplicate
