### ISSUE TITLE
[1.6.0-r9 (69)/Sony z2(6.0.1)/Lomotif is not saved to gallery

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#644] opened 2016-11-20 10:14 UTC
Frequency: Every time
Steps:

- launch the app
- sign in with valid user name and password
- press on start button
- select any image and music 
- click on export 
- type any text and press on make lomotif

note: make sure that" saved to gallery check box" is checked

expected Result:
Lomotif is saved to  telephone gallery

Actual Result:
Lomotif is not saved to telephone gallery

**Comment by hiteshbheda** [comment] 2016-11-20 17:24
@xiuie I can reproduce this issue for build [1.6.0-r9 (69)] on Asus Zenfone Go / Android 5.1

Exported lomotif does not save to Lomotif-staging folder at camera roll folder

**Comment by testershub** [comment] 2016-11-21 05:40
@xiuie Duplicate of #558

**Closed as completed** 2016-11-25 06:21 UTC
Labels: Critical (bug), Reproducible

**Comment by Dipamit** [comment] 2016-11-25 12:46
@xiuie: I can reproduce this issue on Xiaomi RedMi Note 3/5.1.1 and Nexus 6/7.0 for build 1.6.0-r16(76)

**Comment by hiteshbheda** [comment] 2016-12-02 06:06
@xiuie I can still reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by testershub** [comment] 2016-12-02 09:39
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Samsung Galaxy Note 4 / 6.0.1.

**Comment by ayaadel87** [comment] 2016-12-02 09:52
@xiuie :I can still reproduce this issue for build [1.6.0-r22 (82) on sony z2(6.0.1)

**Comment by hiteshbheda** [comment] 2016-12-02 09:57
@xiuie I can still reproduce this issue for build [1.6.0-r22 (82)] on Asus Zenfone Go / Android 5.1

Issue is reproducible even when user is logged in or logged out

**Comment by ayaadel87** [comment] 2016-12-02 10:15
@xiuie : can still reproduce this issue for build [1.6.0-r22 (82) on sony z2(6.0.1)

**Comment by xiuie** [comment] 2016-12-02 10:26
Reproducible on [1.6.0-r22 (82) on Lomo.HW (kyocera)

**Comment by testershub** [comment] 2016-12-02 12:21
@xiuie Verified. Issue is resolved for version [1.6.0-r23(83)]
