### ISSUE TITLE
[1.1.2(22)] Samsung Galaxy Note 4/6.0.1, Samsung Galaxy S4/5.0.1- Thumbnails are not displayed on "Add Photos & Videos" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-android-issues#206] opened 2016-06-16 07:16 UTC
Frequency: Every time.

Action: 
1. Launch the application. 
2. Tap on "Start" button.
3. Check if thumbnails are displayed on "Album" and "Motif" tab.

Expected result: Thumbnails of the folders should be displayed on "Add Photos & Videos" screen.

Actual result: Thumbnails are not displayed.

Refer screenshot for more information.

**Comment by testershub** [comment] 2016-06-16 07:18
![thumbnail](https://cloud.githubusercontent.com/assets/18608449/16108426/a446b1dc-33c0-11e6-9dd9-496ca9c6f198.jpg)

**Comment by vysohanych** [comment] 2016-06-16 14:01
It's duplicate of #173

**Closed as completed** 2016-06-17 05:57 UTC
Labels: Duplicate
