### ISSUE TITLE
Social account icons, Instagram and Facebook are not working in My Video page.

### ISSUE THREAD

**Issue by vinay97t** [Lomotif/lomotif-android-issues#51] opened 2016-04-04 09:52 UTC
Steps to reproduce: 
1. Launch the application.
2. In "Get Started" Page tap on the Start button. 
3. Check whether Instagram and Facebook options are working or not.

Actual result: Intagram and Facebook options are not working.

Expected result: Instagram and Facebook options should work.

Environment: Micromax P480/ android 5.0.1 
![screenshot_2016-04-04-15-08-34](https://cloud.githubusercontent.com/assets/12474351/14244493/ff06af86-fa78-11e5-811b-8bd3975e0980.png)

**Comment by xiuie** [comment] 2016-04-04 16:59
@jpaulo1205 Spoke to Paul. Not a necessary feature for launch but do hide the options if we can't build it in time.

**Comment by hiteshbheda** [comment] 2016-04-04 17:06
@xiuie @jpaulo1205 Duplicate of #13

**Closed as completed** 2016-04-07 15:27 UTC
Labels: Low (bug)
