### ISSUE TITLE
[1.6.0-r18 (78)]/Sony z2(6.0.1)/ App hangs  when user click on"Setting"icon

### ISSUE THREAD

**Issue by ayaadel87** [Lomotif/lomotif-android-issues#687] opened 2016-12-01 15:32 UTC
Frequency: Every time
**Steps:**
-Download the latest build
-sign in with valid credentials
-Click on setting gear at top of the page

**Expected result:**
Setting page is opened successfully

**Actual Result:**
Setting page keeps loading

**Comment by hiteshbheda** [comment] 2016-12-01 16:00
@xiuie  I can't reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**Comment by ayaadel87** [comment] 2016-12-01 16:18
@hiteshbheda : here is a link to video recording, 
https://drive.google.com/file/d/0B12VjRgvbAD0N3JwMFFwM2JsaU0/view?usp=sharing
pleas try it again as its happens with me every time i click on setting option even when i removed and installed the build again

**Comment by hiteshbheda** [comment] 2016-12-01 16:32
@xiuie @ayaadel87 I can't exactly reproduce this issue for build [1.6.0-r18 (78)] on Asus Zenfone Go / Android 5.1

**When I click on Setting Gear "Loading" process starts and continue and never ending.**

**Comment by ayaadel87** [comment] 2016-12-01 16:40
@hiteshbheda  @xiuie : yes that's what exactly is happening with me  also, it keeps loading
so i think it is an issue

**Comment by hiteshbheda** [comment] 2016-12-02 08:36
@xiuie This issue has been resolved in build [1.6.0-r18 (78)] 

Close it for [1.6.0-r18 (78)]

**Closed as completed** 2016-12-02 09:13 UTC
Labels: High (bug), Reproducible
