### ISSUE TITLE
[1.0.13] Sony xPeria Z / 5.1.1 - Close Button (X) Bug - At export screen, Close button not working

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-android-issues#5] opened 2016-03-15 17:43 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select photos from Camera folder from My Video tab
4. Select any song from Find Music tab
5. Click on Export button
6. Click on Close button (top right corner on the screen)

Expected result: Export lomotif window / screen should be closed when clicked on close button

Actual result: There is no effect when clicked on Close button on Export screen

![screenshot_2016-03-15-23-13-14_338x600](https://cloud.githubusercontent.com/assets/9691390/13787838/8d987bc4-eb03-11e5-84c1-04a5d6e25726.jpg)

**Comment by jpaulo1205** [comment] 2016-03-23 09:13
Note: Fixed for next build (1.0.14)

**Comment by vysohanych** [comment] 2016-03-31 15:22
@xiuie @jpaulo1205 I can reproduce this issue on build 1.0.14 (Asus Nexus 7 Android 5.1.1). User should tap many times to close export screen.

Video: [Recording #60.zip](https://github.com/Lomotif/lomotif-android-issues/files/197948/Recording.60.zip)

**Comment by hiteshbheda** [comment] 2016-03-31 15:55
@xiuie @jpaulo1205 @vysohanych **I can't replicate this exactly** in build [1.0.14] with Sony xPeria Z / Android 5.1.1.

**In a single click, Close button does not work properly. To cancel screen it requires minimum 12 to 15 clicks on cancel button.**

**Comment by jpaulo1205** [comment] 2016-04-07 08:43
Made a small fix to increase clickable area for the close button

Note: Fix is in Build 1.0.16

**Comment by vysohanych** [comment] 2016-04-16 21:09
I can't reproduce it on build 1.0.18 on Asus Nexus 7 Android 5.1.1

**Closed as completed** 2016-04-28 22:36 UTC
Labels: High (bug)
